language: objective-c
osx_image: xcode8.2
branches:
  except:
    - gh-pages
before_install:
- carthage bootstrap --platform iOS
- gem install slather jazzy -N
script: xcodebuild test -project Relay.xcodeproj -scheme Relay -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,OS=10.2,id=22FA2149-1241-469C-BF6D-462D3837DB72'
notifications:
  slack:
    secure: REmY4XnYQ5QDu49J3co/VjHQ92DccFPVo9vBobWvcRzqZ03ph0v2zcqIDrVlwc1as1eZ+FAXhJ2tCrEbTax14er1DTXyZPT3Ger1Vmdn2E543D/LwCIaokzPc5quWB8pRy2C6TIzOUAarQ59BkJkGe6yP5VSk3TmpkmRleFT3+oMu+CqTqTuUcsXPRsGAlNMnN24NMhVHPBMXOFTZAEzgDKUBxYhUZTFk//dBVUgXZOOo8dSw1dKJnu85noUGwj14rtBaYa5e1u6cAulh/cDaU8K6x9WnylmU7Jg3kaTR5fYpjxuD8IB0DthIURm3MyyoyS+e0RJxoNxl4NE3aN+b9c2nXyQgiz+me8k80Ah1gMh6GAmUgHsPMPnj9avEI15S22t4pUI9I43TEbzGZ6N0+B34jlVWCImioYCTLsrPh0IA8H4xvrlqla58f4nukd1N4gw1vR78N8Repx4PfRb/LfSP0hYI0yoAjSpmzaERKsMPI6bbYuLxUbidIVTLuFcrJfwgs2uTsEeAQZLStwt7S9v1nKKP+buSbi8B5iD5EcEsNao4nqIIT95tDFHZ6zvbrlVT/oiQPdEk1dbxYIyjLe3WbU9bNO59LgWX5Ap96yOk/l5lNJBpdPL2xCm1OR1umHotr84lowQFE4hl8z2EMy23BOIdgkErqpcI5vMpyw=
after_success: 
- slather
- jazzy
- git branch -b origin/gh-pages gh-pages
- mv docs/* .
- rm -r docs
- git add .
- git commit -m "Documentation update for commit $TRAVIS_COMMIT during CI build #$TRAVIS_BUILD_NUMBER"
- git push -f -q https://ekimia:$GITHUB_TOKEN@github.com/zerofinancial/relay gh-pages &2>/dev/null
env:
  global:
    secure: aWsunKP+6/7GpZZAEgMOjMjX2ZsfdPab0E4j4EC7YOY5A/medKoRjLf4IQCmfVumJ/MG1tRSwxIOjq5+egPAk9jrJGvqti/isf2/0ZZDt+vFENLCKR1ccIZ8XjEHaGXJZ8KrXhGfRaxEMjdpF6T5iAzPQC3koOlyBLpsQxwpz3Hc8EYaAx4mUsj8hjSg8MUINvfJAIE1vOwV2b+TvnwamV2R4S51frb56CpHorg9IhoFsr8TQ78uQTtyxqdsMtVyt0HHpnxTml4eUzfBB00XUfLzt3POivveSphp9tQ3o5ZvC3o5KDbOJFJW7Kn3TC9HBxjUjnCjRJMaVfcikgf33E759Y2vUVFjTZJtL9Zb2Gbq/LDsczTEQ6Y3IA9Y35tJqJk4kyfUnicWoPGxqF3L2mXeKlYGG+WIdW1qR/MtrYVgTF2CSKdwKdpLCz4tYzx5A8xQ/HbD3ktwFoZwxUAGcmPrK5fFtrIJW03BabeYqOLzd7vS0JzO1V8yKUzWlanutVOlfQ/ublO5yB2+Tzpc5bUamL15+JI6Y4dtZa2HoFz07YA9NsxDbImOMnmOKov0mbJY0HVtmDW1pqUBOEltefCSq3K8aLvu+CoF7vF9W25OXdkV3TSGGd2KfKQ5UApqNx95SHjisCv/QbR9mJL8+3H1W2dkBG3sZCDXc4U8alI=
