git:
  submodules: false
language: objective-c
osx_image: xcode8.3
branches:
  except:
  - gh-pages
before_install:
- openssl aes-256-cbc -K $encrypted_6ae9c2fab656_key -iv $encrypted_6ae9c2fab656_iv
  -in deploy_key.enc -out deploy_key -d
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- gem install slather jazzy fastlane -N
- brew install blender/homebrew-tap/rome
script: bash build.sh
notifications:
  slack:
    secure: REmY4XnYQ5QDu49J3co/VjHQ92DccFPVo9vBobWvcRzqZ03ph0v2zcqIDrVlwc1as1eZ+FAXhJ2tCrEbTax14er1DTXyZPT3Ger1Vmdn2E543D/LwCIaokzPc5quWB8pRy2C6TIzOUAarQ59BkJkGe6yP5VSk3TmpkmRleFT3+oMu+CqTqTuUcsXPRsGAlNMnN24NMhVHPBMXOFTZAEzgDKUBxYhUZTFk//dBVUgXZOOo8dSw1dKJnu85noUGwj14rtBaYa5e1u6cAulh/cDaU8K6x9WnylmU7Jg3kaTR5fYpjxuD8IB0DthIURm3MyyoyS+e0RJxoNxl4NE3aN+b9c2nXyQgiz+me8k80Ah1gMh6GAmUgHsPMPnj9avEI15S22t4pUI9I43TEbzGZ6N0+B34jlVWCImioYCTLsrPh0IA8H4xvrlqla58f4nukd1N4gw1vR78N8Repx4PfRb/LfSP0hYI0yoAjSpmzaERKsMPI6bbYuLxUbidIVTLuFcrJfwgs2uTsEeAQZLStwt7S9v1nKKP+buSbi8B5iD5EcEsNao4nqIIT95tDFHZ6zvbrlVT/oiQPdEk1dbxYIyjLe3WbU9bNO59LgWX5Ap96yOk/l5lNJBpdPL2xCm1OR1umHotr84lowQFE4hl8z2EMy23BOIdgkErqpcI5vMpyw=
after_success:
- slather
env:
  global:
  - ENCRYPTION_LABEL: 6ae9c2fab656
  - COMMIT_AUTHOR_EMAIL: robots@zerofinancial.com
  - secure: CBLC8BAE3elfglTmO0T6R/XXpxJdT9XyT1lcRG8tpe/zp4dDfo/vOtvNLCtkSSu5QgpTpMDfiVbTiPZPaVEMQB7kXn3morMz8hB+mnVUmyFcwJm9tJFSz791q5BLzLQ6/JRTntHkCH/SR2Ob9KgL5IoDa2C5WGF9TOAi//XGGApVZKKx9qr1F3e8WoZHSkb5oG6QhmAXdTnvyGavJqTgdblbV3h+OB2F1WqY7us/juBZtu0RvHuyUFJSOuab2cYbsvwTKsIQ+sqHvI5wucVUjwAYxYHssCDPYEA6KlElwqiGoFNDuzpOM2ZdDjYzm/WEXr7FTT+VoSd+M+6L7wPQ+buzvzZIL+uT9eoBZsUj+N04DnKZt4LqpbynaaOAnHyPJLrqC7dsbFs0O5Lzk2nOE1pNi+rcEXa4E5l8xD8rp0XJmNOvBOwURAIA0PT7qaBIqHz2h/OYiLbXHoeJPIQfrKhPOcDWt4FdYBJMX35BCpVBpdCAfqSSYwZzluIHA0M5ZP6XxeFJpJer+13/fTWTDkAXwMvyPHv8qB/pZgMo60cBJwXcX6DYx7CgM13UWwIns7SSGIlg1Z9FZ07VimEFGgoztt0luLYMVKkBfZf0IBWp3sSQ1D7loT0pc7+4BID44w9/wJd+ZWPim74kZtp/y71gPabCN+AjNdNP7oYTkk0=
  - secure: CZHAfpC5m1SGabc/XrRjicNIAfDWJgm/p4DFgCbuKacV9U+AsSDUSheYWkpphN4lw2vLOSG7nYZUVelOFP5roJiqFFC8kdCjB8unnAjhPqbHyjJ0wzQgQoKU5FS8VBp7qj6StG5yI3DQ0g48BuQ7oQ9t+iiqwwyxRE6J/qE2ZDp9cbCgQGRYGHFTZ3JH38zDH4R1E/uU7gK1bvPi1VUxmJGZD7IZKDPIpolM+W79CKOTszuuTKuUqESpB34mhjd1jNMOHHmH0cMgyerKAIDK/1b7GkKSPDeQDRuuMGUVfzBdhaqkMCVUHCmRcU43y/UTx10lIfWygVTIETdx3Q+3QRXthUP0eLR0ymBOGvvth733egy7vYvAWf8sDUTR706ae3U5nRP/rxmBjjgPUPZxr/lSP1B83SmDd0wNAQaxxLvYgfPviHNSM1e8/sg46F3r8EylWW/k6OrYoFQzL1PUijDf6Y9Oaj211ID7sY0QrhDQFKP3G31yFkMOlG0ycYd4zw/33m9tTSPuvskHFmOrij7eKwt3WAcrAGLQsauBAZ3pUlOghF0h/EkeKVOVGVqgD+DbxDwWw4um4KgvMWEZ4CBBp1R96aJhZnH6mb67P7KhYwkp5ycO0TJwT4ppSPB9BN0Vg8O++L0PhdqkfHKa9boqeZKq9ocKKoAA+GD7/zQ=
